### ISSUE TITLE
Update test case results to JIRA Zephyr

### ISSUE THREAD

**Issue by AJ-72** [dipjyotimetia/HybridTestFramework#318]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be good to have an integration with test case management systems like JIRA Zephyr within the framework, so that the status of the test case will be updated automatically after every execution. 

This can be achieved either via REST APIs within this framework or by reusing the existing solutions like https://github.com/ctco/zephyr-sync

**Describe alternatives you've considered**

**Additional context**
Ideally this feature can get extended to support other test case management tools as well like TFS or QTest

**Comment by dipjyotimetia** [comment]
hey @AJ-72  thanks for reching out, dont know how i missed this request, i will definately try to get some time to implement this feature..
I have some plans to include support for tools like
* Jira x-ray
* QTest
* Zephyr

Again more than happy to get a pr having some of this feature, we can discuss about the design as well 👍
