### ISSUE TITLE
Adding Github Action to trigger Test Suite. 

### ISSUE THREAD

**Issue by heyrmi** [dipjyotimetia/HybridTestFramework#595]
**Is your feature request related to a problem? Please describe.**
As companies moving away from Jenkins to Github Actions for CI, thus it will be one good thing if we can have the feature of running our test suites directly from Github Actions using workflows. 

**Describe the solution you'd like**
If some code change or merge is performed (say for eg. in the repo of some company), and that code is hosted on Github enterprise edition then its good to have the Github Actions to trigger Smoke/Regression suite automatically. 
 
**Describe alternatives you've considered**
NA

**Additional context**
<img width="1476" alt="Screenshot 2022-06-18 at 09 16 42" src="https://user-images.githubusercontent.com/42892759/174421693-ccf5d813-93dd-465f-8529-4373346a6da8.png">

This is one is for maven project.

**Comment by dipjyotimetia** [comment]
This is already addressed and part of the framework
https://github.com/dipjyotimetia/HybridTestFramework/blob/master/.github/workflows/gradle.yml

**Comment by heyrmi** [comment]
Closing this as this feature is already there.
